### ISSUE TITLE
BATTLE OF RUNTEQ Vol2レビュー

### ISSUE THREAD

**Issue by hisaju** [koutapro1/sales_calender#48]
まだ制作途中だと思うので、書き方で気になったところだけ記載しますね。完成後にレビュー会などでまたレビューさせてください。

----
https://github.com/koutapro1/sales_calender/blob/c6edca9f5f47dd65774d853582967adac53b34e5/app/controllers/scores_controller.rb#L8

これってcurrent_userですよね？

https://github.com/koutapro1/sales_calender/blob/c6edca9f5f47dd65774d853582967adac53b34e5/app/controllers/scores_controller.rb#L6-L7

こちら
```ruby
@scores = current_user.scores. get_scores_in_current_page(start_date)
```
と書かれるとよいのかなと

https://github.com/koutapro1/sales_calender/blob/c6edca9f5f47dd65774d853582967adac53b34e5/app/models/score.rb#L9

こちらbetween?メソッドを使うともう少しすっきり書けるかなと思いますので、お試しください。
https://blog.toshimaru.net/datetime-range-check/

**Comment by koutapro1** [comment]
@hisaju お忙しい中レビューしていただきありがとうございます。ご指摘いただいた箇所は、途中で気づいてdevelopment ブランチで修正済みです。
完成後、レビュー会でレビューよろしくお願いいたします。
